### ISSUE TITLE
License Error

### ISSUE THREAD

**Issue by shiebl** [bitmovin/bitmovin-player-tizen-demo#1]
Tizen IDE 2.4

Everytime I try to get this to work, it says 

```
js/main.js (38) :On Error: {"type":"onError","timestamp":1533885541335,"code":1016,"message":"<strong>License Error</strong></br> Field [domain] is not set or null."}
js/main.js (28) :Successfully created bitmovin player instance
js/main.js (35) :On Warning: {"code":5008,"message":"Playback could not be started, reason: The play call was interrupted by abort","timestamp":1533885541607,"type":"onWarning"}
```

The license key is correct and inserted in main.js.
Also I wonder what the "app_id" in the tweaks section is supposed to be?

Thanks in advance for your help!

**Comment by zachmanc** [comment]
@shiebl we have are target a fix by the end of September. I will let you know once its available

**Comment by zachmanc** [comment]
@shiebl this issue you be fixed now. Please validate
